[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_*
testpaths = core/tests core/features ui/tests ui/features
addopts = --no-migrations
