# Generated by Django 6.0.3 on 2026-07-15 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_student_parent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curriculum_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.TextField(blank=True, null=True)),
                ('coin_value', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'toys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_spent', models.PositiveIntegerField()),
                ('redeemed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'toy_redemptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSpeedPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_rate', models.SmallIntegerField(default=100)),
                ('line_gap', models.SmallIntegerField(default=630)),
                ('danger_zone', models.BooleanField(default=False)),
                ('dz_voice_rate', models.SmallIntegerField(default=160)),
                ('dz_line_gap', models.SmallIntegerField(default=30)),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='speed_prefs', to='api.appuser')),
            ],
            options={
                'db_table': 'student_speed_prefs',
            },
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Learning',
        ),
    ]
