# Generated by Django 6.0.3 on 2026-07-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_student_speed_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentspeedprefs',
            name='voice_lang',
            field=models.CharField(default='en-US', max_length=20),
        ),
        migrations.AddField(
            model_name='studentspeedprefs',
            name='voice_name',
            field=models.CharField(default='en-US-Neural2-D', max_length=60),
        ),
        migrations.AlterField(
            model_name='studentspeedprefs',
            name='dz_line_gap',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='studentspeedprefs',
            name='line_gap',
            field=models.SmallIntegerField(default=500),
        ),
    ]
